feat: simple docker support

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,7 +1,33 @@
-FROM --platform=$TARGETPLATFORM node:16-alpine3.15
-EXPOSE 8088
-RUN mkdir -p /data/api
-COPY app.js /data/api/app.js
-COPY package.json /data/api/package.json
-RUN npm install --prefix /data/api
-CMD ["node", "/data/api/app.js"]
+FROM node:20-alpine AS base
+
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY . .
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# RUN yarn build
+RUN corepack enable && corepack prepare pnpm@latest --activate
+RUN pnpm build
+
+# If using npm comment out above and use below instead
+# RUN npm run build
+
+FROM node:20-alpine
+
+ENV NODE_ENV production
+
+COPY --from=base /app/node_modules ./node_modules
+COPY --from=base /app/package*.json ./
+COPY --from=base /app/dist ./dist
+
+EXPOSE 8080
+
+ENV PORT 8080
+
+CMD ["npm", "run", "start"]
